version: "3.8"

services:
  online_shop:

    build:
      context: . 

    container_name: onlineapp
    
    ports:
      - "5173:5173"
     
    restart: always

    networks:
      - onlineshop     
 

networks:
  onlineshop:
    driver: bridge

      
